-- =====================================================================
-- بيتنا / OurNest Finance — ONE-SHOT DATABASE SETUP
-- Paste this whole file into Supabase → SQL Editor → New query → Run.
-- Run it ONCE on a fresh project. It is the concatenation of
-- supabase/migrations/*.sql (generated by scripts/build-setup-sql.sh).
-- =====================================================================

-- >>> 20261009000100_foundation.sql
-- =====================================================================
-- OurNest Finance (بيتنا) — Foundation: extensions, enums, profiles,
-- households, membership, invitations and core helper functions.
--
-- Money is stored as BIGINT minor units (fils, 1 AED = 100 fils).
-- Calendar dates are stored as DATE values in Dubai local time.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------
create type public.record_visibility as enum ('shared', 'private');
create type public.payment_method as enum ('cash', 'debit_card', 'credit_card', 'bank_transfer', 'apple_pay', 'other');
create type public.account_kind as enum ('bank', 'credit_card', 'cash', 'wallet', 'savings', 'other');
create type public.income_kind as enum ('salary', 'freelance', 'bonus', 'other');
create type public.income_frequency as enum ('monthly', 'one_time');
create type public.bill_frequency as enum ('weekly', 'monthly', 'quarterly', 'yearly');
create type public.bill_kind as enum ('rent', 'car', 'utilities', 'internet', 'mobile', 'insurance', 'subscription', 'installment', 'other');
create type public.invitation_status as enum ('pending', 'accepted', 'revoked');
create type public.goal_kind as enum ('emergency', 'home', 'travel', 'car', 'apartment', 'vacation', 'other');

-- ---------------------------------------------------------------------
-- Generic trigger: keep updated_at fresh
-- ---------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- Profiles: the minimal identity a spouse may see about the other.
-- ---------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default '' check (char_length(display_name) <= 60),
  avatar_color text not null default 'emerald'
    check (avatar_color in ('emerald', 'sage', 'sand', 'rose', 'sky', 'violet')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- User settings: strictly private to the owner (theme, numerals,
-- notification preferences).
-- ---------------------------------------------------------------------
create table public.user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  theme text not null default 'system' check (theme in ('system', 'light', 'dark')),
  numerals text not null default 'latn' check (numerals in ('latn', 'arab')),
  default_visibility public.record_visibility not null default 'shared',
  notify_shared_expenses boolean not null default true,
  notify_bills boolean not null default true,
  notify_budget boolean not null default true,
  bill_reminder_days integer not null default 3 check (bill_reminder_days between 0 and 14),
  updated_at timestamptz not null default now()
);

create trigger user_settings_touch before update on public.user_settings
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Households & membership (max two members: a married couple)
-- ---------------------------------------------------------------------
create table public.households (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'بيتنا' check (char_length(name) between 1 and 60),
  currency text not null default 'AED' check (currency = 'AED'),
  timezone text not null default 'Asia/Dubai',
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger households_touch before update on public.households
  for each row execute function public.touch_updated_at();

create table public.household_members (
  household_id uuid not null references public.households (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  -- Informational only. Both members have identical permissions.
  joined_via text not null default 'created' check (joined_via in ('created', 'invitation')),
  joined_at timestamptz not null default now(),
  primary key (household_id, user_id),
  -- One household per user keeps the privacy model unambiguous.
  constraint household_members_one_household unique (user_id)
);

create index household_members_household_idx on public.household_members (household_id);

create or replace function public.enforce_household_capacity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Serialise concurrent joins on the same household.
  perform 1 from public.households where id = new.household_id for update;
  if (select count(*) from public.household_members where household_id = new.household_id) >= 2 then
    raise exception 'household_full' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger household_members_capacity before insert on public.household_members
  for each row execute function public.enforce_household_capacity();

-- ---------------------------------------------------------------------
-- Invitations. Only a SHA-256 hash of the token is stored.
-- ---------------------------------------------------------------------
create table public.invitations (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  email text not null check (email = lower(email) and position('@' in email) > 1),
  token_hash text not null unique,
  invited_by uuid not null references auth.users (id) on delete cascade,
  status public.invitation_status not null default 'pending',
  expires_at timestamptz not null default now() + interval '7 days',
  accepted_by uuid references auth.users (id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create index invitations_household_idx on public.invitations (household_id, status);

-- ---------------------------------------------------------------------
-- Helper predicates used by RLS policies. SECURITY DEFINER avoids
-- recursive policy evaluation on household_members.
-- ---------------------------------------------------------------------
create or replace function public.is_household_member(p_household_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.household_members m
    where m.household_id = p_household_id
      and m.user_id = (select auth.uid())
  );
$$;

create or replace function public.my_household_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select m.household_id from public.household_members m
  where m.user_id = (select auth.uid())
  limit 1;
$$;

create or replace function public.shares_household_with(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.household_members a
    join public.household_members b on b.household_id = a.household_id
    where a.user_id = (select auth.uid())
      and b.user_id = p_user_id
  );
$$;

-- Read rule shared by every visibility-aware table:
--   shared records  -> any member of the record's household
--   private records -> the owner only
create or replace function public.can_read_record(
  p_household_id uuid,
  p_owner_id uuid,
  p_visibility public.record_visibility
)
returns boolean
language sql
stable
set search_path = ''
as $$
  select
    (p_visibility = 'private' and p_owner_id = (select auth.uid()))
    or (p_visibility = 'shared' and public.is_household_member(p_household_id));
$$;

-- Write rule: identical to read, but the caller must still belong to the
-- household (a member who left cannot keep editing shared data).
create or replace function public.can_write_record(
  p_household_id uuid,
  p_owner_id uuid,
  p_visibility public.record_visibility
)
returns boolean
language sql
stable
set search_path = ''
as $$
  select public.is_household_member(p_household_id)
    and (p_visibility = 'shared' or p_owner_id = (select auth.uid()));
$$;

-- Ownership columns are immutable after creation, and only the owner may
-- change who can see a record. This stops a spouse from "claiming" or
-- hiding the other spouse's shared records.
create or replace function public.guard_record_ownership()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.owner_id is distinct from old.owner_id then
    raise exception 'owner_immutable' using errcode = 'P0001';
  end if;
  if new.household_id is distinct from old.household_id then
    raise exception 'household_immutable' using errcode = 'P0001';
  end if;
  if new.visibility is distinct from old.visibility
     and old.owner_id is distinct from (select auth.uid())
     and (select auth.uid()) is not null then
    raise exception 'only_owner_can_change_visibility' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- New auth user -> profile + settings rows
-- ---------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1), ''), 60)
  )
  on conflict (id) do nothing;

  insert into public.user_settings (user_id) values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- >>> 20261009000200_finance.sql
-- =====================================================================
-- OurNest Finance — financial data model
-- Every visibility-aware table carries (household_id, owner_id, visibility).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Financial accounts (labels for where money moves; no balances are
-- inferred so nothing is ever fabricated).
-- ---------------------------------------------------------------------
create table public.financial_accounts (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  visibility public.record_visibility not null default 'private',
  name text not null check (char_length(name) between 1 and 60),
  kind public.account_kind not null default 'bank',
  institution text check (char_length(institution) <= 60),
  last4 text check (last4 ~ '^[0-9]{4}$'),
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index financial_accounts_household_idx on public.financial_accounts (household_id, visibility);
create index financial_accounts_owner_idx on public.financial_accounts (owner_id);

-- ---------------------------------------------------------------------
-- Categories (shared household categories + private custom ones)
-- ---------------------------------------------------------------------
create table public.categories (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  visibility public.record_visibility not null default 'shared',
  parent_id uuid references public.categories (id) on delete restrict,
  name text not null check (char_length(name) between 1 and 40),
  icon text not null default 'tag' check (char_length(icon) <= 30),
  color text not null default 'emerald' check (char_length(color) <= 20),
  -- Stable semantic key used by transparent insight rules (e.g. 'dining').
  system_key text check (system_key ~ '^[a-z_]{2,30}$'),
  sort_order integer not null default 100,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_no_self_parent check (parent_id is null or parent_id <> id)
);
create index categories_household_idx on public.categories (household_id, visibility, is_archived);
create unique index categories_unique_name on public.categories
  (household_id, visibility, (case when visibility = 'private' then owner_id end), parent_id, name)
  nulls not distinct;

-- ---------------------------------------------------------------------
-- Default budget template (data, not logic). Copied into each new
-- household where it becomes fully editable household data.
-- ---------------------------------------------------------------------
create table public.default_budget_template (
  system_key text primary key,
  name text not null,
  icon text not null,
  color text not null,
  planned_minor bigint not null check (planned_minor >= 0),
  sort_order integer not null
);

create table public.default_budget_settings (
  id boolean primary key default true check (id),
  total_allocation_minor bigint not null check (total_allocation_minor >= 0)
);

-- ---------------------------------------------------------------------
-- Monthly household budgets (always shared — it's an allocation,
-- never a representation of anyone's income).
-- ---------------------------------------------------------------------
create table public.budgets (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  month date not null check (extract(day from month) = 1),
  total_allocation_minor bigint not null default 0 check (total_allocation_minor >= 0),
  note text check (char_length(note) <= 300),
  created_by uuid default auth.uid() references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint budgets_one_per_month unique (household_id, month)
);

create table public.budget_items (
  id uuid primary key default gen_random_uuid(),
  budget_id uuid not null references public.budgets (id) on delete cascade,
  household_id uuid not null references public.households (id) on delete cascade,
  category_id uuid not null references public.categories (id) on delete cascade,
  planned_minor bigint not null default 0 check (planned_minor >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint budget_items_unique_category unique (budget_id, category_id)
);
create index budget_items_household_idx on public.budget_items (household_id);

-- ---------------------------------------------------------------------
-- Household contributions: what each spouse chooses to put into the
-- household pot. Independent from (and never derived from) income.
-- ---------------------------------------------------------------------
create table public.household_contributions (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  effective_month date not null check (extract(day from effective_month) = 1),
  monthly_amount_minor bigint not null check (monthly_amount_minor >= 0),
  note text check (char_length(note) <= 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint household_contributions_unique unique (household_id, user_id, effective_month)
);

-- ---------------------------------------------------------------------
-- Private income — has no visibility column on purpose: it can never be
-- shared through the data model.
-- ---------------------------------------------------------------------
create table public.income_sources (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  household_id uuid references public.households (id) on delete set null,
  name text not null check (char_length(name) between 1 and 60),
  kind public.income_kind not null default 'salary',
  frequency public.income_frequency not null default 'monthly',
  amount_minor bigint not null check (amount_minor > 0),
  -- Monthly: first month it applies. One-time: the date it was received.
  starts_on date not null,
  ends_on date,
  account_id uuid references public.financial_accounts (id) on delete set null,
  note text check (char_length(note) <= 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint income_dates check (ends_on is null or ends_on >= starts_on)
);
create index income_sources_owner_idx on public.income_sources (owner_id, starts_on);

-- ---------------------------------------------------------------------
-- Recurring bills
-- ---------------------------------------------------------------------
create table public.recurring_bills (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  visibility public.record_visibility not null default 'shared',
  name text not null check (char_length(name) between 1 and 60),
  kind public.bill_kind not null default 'other',
  category_id uuid references public.categories (id) on delete set null,
  amount_minor bigint not null check (amount_minor > 0),
  is_variable boolean not null default false,
  frequency public.bill_frequency not null default 'monthly',
  interval_count integer not null default 1 check (interval_count between 1 and 12),
  -- First due date. Later due dates are computed from this anchor.
  anchor_date date not null,
  end_date date,
  reminder_days integer not null default 3 check (reminder_days between 0 and 14),
  autopay boolean not null default false,
  is_active boolean not null default true,
  note text check (char_length(note) <= 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bill_dates check (end_date is null or end_date >= anchor_date)
);
create index recurring_bills_household_idx on public.recurring_bills (household_id, visibility, is_active);

-- ---------------------------------------------------------------------
-- Installment plans & payments
-- ---------------------------------------------------------------------
create table public.installment_plans (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  visibility public.record_visibility not null default 'shared',
  name text not null check (char_length(name) between 1 and 60),
  lender text check (char_length(lender) <= 60),
  category_id uuid references public.categories (id) on delete set null,
  -- Total amount payable over the plan (including any fees/interest).
  total_amount_minor bigint not null check (total_amount_minor > 0),
  monthly_amount_minor bigint not null check (monthly_amount_minor > 0),
  -- Amount already paid before tracking started in the app.
  opening_paid_minor bigint not null default 0 check (opening_paid_minor >= 0),
  first_due_date date not null,
  is_active boolean not null default true,
  note text check (char_length(note) <= 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint installment_amounts check (monthly_amount_minor <= total_amount_minor and opening_paid_minor <= total_amount_minor)
);
create index installment_plans_household_idx on public.installment_plans (household_id, visibility, is_active);

-- ---------------------------------------------------------------------
-- Transactions (expenses)
-- ---------------------------------------------------------------------
create table public.transactions (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  visibility public.record_visibility not null default 'shared',
  amount_minor bigint not null check (amount_minor > 0 and amount_minor <= 100000000000),
  category_id uuid not null references public.categories (id) on delete restrict,
  account_id uuid references public.financial_accounts (id) on delete set null,
  payment_method public.payment_method,
  description text check (char_length(description) <= 200),
  occurred_on date not null,
  -- Paying a scheduled bill links the transaction to that occurrence; the
  -- unique index below makes double-counting a bill period impossible.
  bill_id uuid references public.recurring_bills (id) on delete set null,
  bill_period date,
  installment_plan_id uuid references public.installment_plans (id) on delete set null,
  -- Idempotency key generated when the entry sheet opens (double-tap safe).
  client_request_id uuid not null default gen_random_uuid(),
  last_edited_by uuid default auth.uid() references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transactions_client_request_unique unique (client_request_id),
  constraint transactions_bill_period_pair check (bill_id is null or bill_period is not null)
);
create index transactions_household_date_idx on public.transactions (household_id, visibility, occurred_on desc);
create index transactions_owner_date_idx on public.transactions (owner_id, occurred_on desc);
create index transactions_category_idx on public.transactions (category_id);
create unique index transactions_one_payment_per_bill_period
  on public.transactions (bill_id, bill_period) where bill_id is not null;

create table public.installment_payments (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.installment_plans (id) on delete cascade,
  amount_minor bigint not null check (amount_minor > 0),
  paid_on date not null,
  -- Scheduled due date this payment settles (null for an extra payment).
  period date,
  is_extra boolean not null default false,
  transaction_id uuid references public.transactions (id) on delete cascade,
  created_by uuid default auth.uid() references auth.users (id) on delete set null,
  note text check (char_length(note) <= 200),
  created_at timestamptz not null default now(),
  constraint installment_payment_period check (is_extra or period is not null)
);
create unique index installment_payments_one_per_period
  on public.installment_payments (plan_id, period) where period is not null;
create index installment_payments_plan_idx on public.installment_payments (plan_id, paid_on);

-- ---------------------------------------------------------------------
-- Savings goals & contributions
-- ---------------------------------------------------------------------
create table public.savings_goals (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  visibility public.record_visibility not null default 'shared',
  name text not null check (char_length(name) between 1 and 60),
  kind public.goal_kind not null default 'other',
  target_minor bigint not null check (target_minor > 0),
  target_date date,
  monthly_contribution_minor bigint not null default 0 check (monthly_contribution_minor >= 0),
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index savings_goals_household_idx on public.savings_goals (household_id, visibility);

create table public.savings_contributions (
  id uuid primary key default gen_random_uuid(),
  goal_id uuid not null references public.savings_goals (id) on delete cascade,
  -- Negative amounts are withdrawals.
  amount_minor bigint not null check (amount_minor <> 0),
  contributed_on date not null,
  created_by uuid default auth.uid() references auth.users (id) on delete set null,
  note text check (char_length(note) <= 200),
  created_at timestamptz not null default now()
);
create index savings_contributions_goal_idx on public.savings_contributions (goal_id, contributed_on);

-- ---------------------------------------------------------------------
-- Receipts (files live in the private "receipts" storage bucket)
-- ---------------------------------------------------------------------
create table public.receipt_attachments (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references public.transactions (id) on delete cascade,
  storage_path text not null unique,
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'application/pdf')),
  size_bytes integer not null check (size_bytes > 0 and size_bytes <= 10485760),
  uploaded_by uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
create index receipt_attachments_tx_idx on public.receipt_attachments (transaction_id);

-- ---------------------------------------------------------------------
-- Personal notes (owner only, never shareable)
-- ---------------------------------------------------------------------
create table public.personal_notes (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  body text not null default '' check (char_length(body) <= 4000),
  is_pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index personal_notes_owner_idx on public.personal_notes (owner_id, updated_at desc);

-- ---------------------------------------------------------------------
-- updated_at triggers + ownership guards
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'financial_accounts', 'categories', 'budgets', 'budget_items', 'household_contributions',
    'income_sources', 'recurring_bills', 'installment_plans', 'transactions', 'savings_goals', 'personal_notes'
  ] loop
    execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t);
  end loop;

  foreach t in array array[
    'financial_accounts', 'categories', 'recurring_bills', 'installment_plans', 'transactions', 'savings_goals'
  ] loop
    execute format('create trigger %I before update on public.%I for each row execute function public.guard_record_ownership()', t || '_guard', t);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------
-- Referential privacy: a shared record may only reference shared
-- categories/accounts in the same household, so the other spouse never
-- receives a pointer to (or a join through) a private record.
-- ---------------------------------------------------------------------
create or replace function public.check_reference_privacy()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_cat record;
  v_acc record;
  v_parent record;
  v_bill record;
  v_plan record;
begin
  -- (PL/pgSQL does not short-circuit, so column access is nested.)
  if tg_table_name in ('transactions', 'recurring_bills', 'installment_plans') then
    if new.category_id is not null then
      select household_id, owner_id, visibility into v_cat from public.categories where id = new.category_id;
      if not found or v_cat.household_id <> new.household_id then
        raise exception 'category_not_in_household' using errcode = 'P0001';
      end if;
      if v_cat.visibility = 'private' and (new.visibility = 'shared' or v_cat.owner_id <> new.owner_id) then
        raise exception 'shared_record_needs_shared_category' using errcode = 'P0001';
      end if;
    end if;
  end if;

  if tg_table_name = 'transactions' then
    if new.account_id is not null then
      select household_id, owner_id, visibility into v_acc from public.financial_accounts where id = new.account_id;
      if not found or v_acc.household_id <> new.household_id then
        raise exception 'account_not_in_household' using errcode = 'P0001';
      end if;
      if v_acc.visibility = 'private' and (new.visibility = 'shared' or v_acc.owner_id <> new.owner_id) then
        raise exception 'shared_record_needs_shared_account' using errcode = 'P0001';
      end if;
    end if;
    if new.bill_id is not null then
      select household_id, owner_id, visibility into v_bill from public.recurring_bills where id = new.bill_id;
      if not found or v_bill.household_id <> new.household_id
         or (v_bill.visibility = 'private' and (new.visibility = 'shared' or v_bill.owner_id <> new.owner_id)) then
        raise exception 'bill_reference_not_allowed' using errcode = 'P0001';
      end if;
    end if;
    if new.installment_plan_id is not null then
      select household_id, owner_id, visibility into v_plan from public.installment_plans where id = new.installment_plan_id;
      if not found or v_plan.household_id <> new.household_id
         or (v_plan.visibility = 'private' and (new.visibility = 'shared' or v_plan.owner_id <> new.owner_id)) then
        raise exception 'installment_reference_not_allowed' using errcode = 'P0001';
      end if;
    end if;
  end if;

  if tg_table_name = 'categories' then
   if new.parent_id is not null then
    select household_id, owner_id, visibility, parent_id into v_parent from public.categories where id = new.parent_id;
    if not found or v_parent.household_id <> new.household_id or v_parent.parent_id is not null then
      raise exception 'invalid_parent_category' using errcode = 'P0001';
    end if;
    if v_parent.visibility = 'private' and (new.visibility = 'shared' or v_parent.owner_id <> new.owner_id) then
      raise exception 'shared_category_needs_shared_parent' using errcode = 'P0001';
    end if;
   end if;
  end if;

  -- Making a category private while shared records still use it would
  -- leak; block it.
  if tg_table_name = 'categories' and tg_op = 'UPDATE' then
   if old.visibility = 'shared' and new.visibility = 'private' then
    if exists (select 1 from public.transactions where category_id = new.id and visibility = 'shared')
       or exists (select 1 from public.budget_items where category_id = new.id)
       or exists (select 1 from public.categories where parent_id = new.id and visibility = 'shared') then
      raise exception 'category_in_shared_use' using errcode = 'P0001';
    end if;
   end if;
  end if;

  if tg_table_name = 'financial_accounts' and tg_op = 'UPDATE' then
    if old.visibility = 'shared' and new.visibility = 'private' then
      if exists (select 1 from public.transactions where account_id = new.id and visibility = 'shared') then
        raise exception 'account_in_shared_use' using errcode = 'P0001';
      end if;
    end if;
  end if;

  return new;
end;
$$;

create trigger transactions_reference_privacy before insert or update on public.transactions
  for each row execute function public.check_reference_privacy();
create trigger bills_reference_privacy before insert or update on public.recurring_bills
  for each row execute function public.check_reference_privacy();
create trigger plans_reference_privacy before insert or update on public.installment_plans
  for each row execute function public.check_reference_privacy();
create trigger categories_reference_privacy before insert or update on public.categories
  for each row execute function public.check_reference_privacy();
create trigger accounts_reference_privacy before update on public.financial_accounts
  for each row execute function public.check_reference_privacy();

-- Budget items may only point at shared categories of the same household.
create or replace function public.check_budget_item()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_budget_household uuid;
begin
  select household_id into v_budget_household from public.budgets where id = new.budget_id;
  if v_budget_household is null or v_budget_household <> new.household_id then
    raise exception 'budget_household_mismatch' using errcode = 'P0001';
  end if;
  if not exists (
    select 1 from public.categories c
    where c.id = new.category_id and c.household_id = new.household_id and c.visibility = 'shared'
  ) then
    raise exception 'budget_item_needs_shared_category' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger budget_items_check before insert or update on public.budget_items
  for each row execute function public.check_budget_item();

-- Income account must belong to the same owner.
create or replace function public.check_income_account()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.account_id is not null and not exists (
    select 1 from public.financial_accounts a where a.id = new.account_id and a.owner_id = new.owner_id
  ) then
    raise exception 'income_account_not_owned' using errcode = 'P0001';
  end if;
  if tg_op = 'UPDATE' then
    if new.owner_id is distinct from old.owner_id then
      raise exception 'owner_immutable' using errcode = 'P0001';
    end if;
  end if;
  return new;
end;
$$;

create trigger income_sources_check before insert or update on public.income_sources
  for each row execute function public.check_income_account();

-- >>> 20261009000300_rls.sql
-- =====================================================================
-- OurNest Finance — Row Level Security
-- The database is the security boundary. The UI never is.
-- =====================================================================

-- Lock everything down first, then grant only what the app needs.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public revoke execute on functions from public, anon;

grant usage on schema public to authenticated, anon;

grant select, insert, update, delete on
  public.financial_accounts, public.categories, public.budgets, public.budget_items,
  public.household_contributions, public.income_sources, public.recurring_bills,
  public.installment_plans, public.installment_payments, public.transactions,
  public.savings_goals, public.savings_contributions, public.receipt_attachments,
  public.personal_notes
to authenticated;

grant select, update on public.profiles, public.user_settings to authenticated;
grant select, update on public.households to authenticated;
grant select on public.household_members, public.invitations to authenticated;
grant select on public.default_budget_template, public.default_budget_settings to authenticated;

-- Helper predicates are needed inside policies.
grant execute on function
  public.is_household_member(uuid), public.my_household_id(), public.shares_household_with(uuid),
  public.can_read_record(uuid, uuid, public.record_visibility),
  public.can_write_record(uuid, uuid, public.record_visibility)
to authenticated;

-- Enable RLS on every table.
do $$
declare t text;
begin
  foreach t in array array[
    'profiles', 'user_settings', 'households', 'household_members', 'invitations',
    'financial_accounts', 'categories', 'default_budget_template', 'default_budget_settings',
    'budgets', 'budget_items', 'household_contributions', 'income_sources', 'recurring_bills',
    'installment_plans', 'installment_payments', 'transactions', 'savings_goals',
    'savings_contributions', 'receipt_attachments', 'personal_notes'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------
-- Profiles: yourself + your spouse (display name & avatar colour only)
-- ---------------------------------------------------------------------
create policy profiles_select on public.profiles for select to authenticated
  using (id = (select auth.uid()) or public.shares_household_with(id));
create policy profiles_update on public.profiles for update to authenticated
  using (id = (select auth.uid())) with check (id = (select auth.uid()));

-- User settings: owner only
create policy user_settings_select on public.user_settings for select to authenticated
  using (user_id = (select auth.uid()));
create policy user_settings_update on public.user_settings for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- Households: members only. Creation goes through create_household().
create policy households_select on public.households for select to authenticated
  using (public.is_household_member(id));
create policy households_update on public.households for update to authenticated
  using (public.is_household_member(id)) with check (public.is_household_member(id));

create policy household_members_select on public.household_members for select to authenticated
  using (public.is_household_member(household_id));

-- Invitations: visible to household members (token hash is never
-- selected by the app; the column is revoked below).
create policy invitations_select on public.invitations for select to authenticated
  using (public.is_household_member(household_id));
revoke select on public.invitations from authenticated;
grant select (id, household_id, email, invited_by, status, expires_at, accepted_by, accepted_at, created_at)
  on public.invitations to authenticated;

-- Template: readable reference data
create policy template_select on public.default_budget_template for select to authenticated using (true);
create policy template_settings_select on public.default_budget_settings for select to authenticated using (true);

-- ---------------------------------------------------------------------
-- Visibility-aware tables
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'financial_accounts', 'categories', 'recurring_bills', 'installment_plans', 'transactions', 'savings_goals'
  ] loop
    execute format($f$
      create policy %1$s_select on public.%1$I for select to authenticated
        using (public.can_read_record(household_id, owner_id, visibility))
    $f$, t);
    execute format($f$
      create policy %1$s_insert on public.%1$I for insert to authenticated
        with check (owner_id = (select auth.uid()) and public.is_household_member(household_id))
    $f$, t);
    execute format($f$
      create policy %1$s_update on public.%1$I for update to authenticated
        using (public.can_write_record(household_id, owner_id, visibility))
        with check (public.can_write_record(household_id, owner_id, visibility))
    $f$, t);
    execute format($f$
      create policy %1$s_delete on public.%1$I for delete to authenticated
        using (public.can_write_record(household_id, owner_id, visibility))
    $f$, t);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------
-- Budgets (shared allocation — both spouses have equal rights)
-- ---------------------------------------------------------------------
create policy budgets_select on public.budgets for select to authenticated
  using (public.is_household_member(household_id));
create policy budgets_insert on public.budgets for insert to authenticated
  with check (public.is_household_member(household_id));
create policy budgets_update on public.budgets for update to authenticated
  using (public.is_household_member(household_id)) with check (public.is_household_member(household_id));
create policy budgets_delete on public.budgets for delete to authenticated
  using (public.is_household_member(household_id));

create policy budget_items_select on public.budget_items for select to authenticated
  using (public.is_household_member(household_id));
create policy budget_items_insert on public.budget_items for insert to authenticated
  with check (public.is_household_member(household_id));
create policy budget_items_update on public.budget_items for update to authenticated
  using (public.is_household_member(household_id)) with check (public.is_household_member(household_id));
create policy budget_items_delete on public.budget_items for delete to authenticated
  using (public.is_household_member(household_id));

-- ---------------------------------------------------------------------
-- Contributions: both can see; each spouse manages only their own.
-- ---------------------------------------------------------------------
create policy contributions_select on public.household_contributions for select to authenticated
  using (public.is_household_member(household_id));
create policy contributions_insert on public.household_contributions for insert to authenticated
  with check (user_id = (select auth.uid()) and public.is_household_member(household_id));
create policy contributions_update on public.household_contributions for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()) and public.is_household_member(household_id));
create policy contributions_delete on public.household_contributions for delete to authenticated
  using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------
-- Owner-only tables: income & personal notes
-- ---------------------------------------------------------------------
create policy income_select on public.income_sources for select to authenticated
  using (owner_id = (select auth.uid()));
create policy income_insert on public.income_sources for insert to authenticated
  with check (owner_id = (select auth.uid()) and (household_id is null or public.is_household_member(household_id)));
create policy income_update on public.income_sources for update to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy income_delete on public.income_sources for delete to authenticated
  using (owner_id = (select auth.uid()));

create policy notes_select on public.personal_notes for select to authenticated
  using (owner_id = (select auth.uid()));
create policy notes_insert on public.personal_notes for insert to authenticated
  with check (owner_id = (select auth.uid()));
create policy notes_update on public.personal_notes for update to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy notes_delete on public.personal_notes for delete to authenticated
  using (owner_id = (select auth.uid()));

-- ---------------------------------------------------------------------
-- Child tables inherit access from their parent. Sub-selects inside a
-- policy are themselves subject to the parent's RLS.
-- ---------------------------------------------------------------------
create policy installment_payments_select on public.installment_payments for select to authenticated
  using (exists (select 1 from public.installment_plans p where p.id = plan_id));
create policy installment_payments_insert on public.installment_payments for insert to authenticated
  with check (exists (
    select 1 from public.installment_plans p
    where p.id = plan_id and public.can_write_record(p.household_id, p.owner_id, p.visibility)
  ));
create policy installment_payments_update on public.installment_payments for update to authenticated
  using (exists (
    select 1 from public.installment_plans p
    where p.id = plan_id and public.can_write_record(p.household_id, p.owner_id, p.visibility)
  ))
  with check (exists (
    select 1 from public.installment_plans p
    where p.id = plan_id and public.can_write_record(p.household_id, p.owner_id, p.visibility)
  ));
create policy installment_payments_delete on public.installment_payments for delete to authenticated
  using (exists (
    select 1 from public.installment_plans p
    where p.id = plan_id and public.can_write_record(p.household_id, p.owner_id, p.visibility)
  ));

create policy savings_contributions_select on public.savings_contributions for select to authenticated
  using (exists (select 1 from public.savings_goals g where g.id = goal_id));
create policy savings_contributions_insert on public.savings_contributions for insert to authenticated
  with check (exists (
    select 1 from public.savings_goals g
    where g.id = goal_id and public.can_write_record(g.household_id, g.owner_id, g.visibility)
  ));
create policy savings_contributions_update on public.savings_contributions for update to authenticated
  using (exists (
    select 1 from public.savings_goals g
    where g.id = goal_id and public.can_write_record(g.household_id, g.owner_id, g.visibility)
  ))
  with check (exists (
    select 1 from public.savings_goals g
    where g.id = goal_id and public.can_write_record(g.household_id, g.owner_id, g.visibility)
  ));
create policy savings_contributions_delete on public.savings_contributions for delete to authenticated
  using (exists (
    select 1 from public.savings_goals g
    where g.id = goal_id and public.can_write_record(g.household_id, g.owner_id, g.visibility)
  ));

create policy receipts_select on public.receipt_attachments for select to authenticated
  using (exists (select 1 from public.transactions t where t.id = transaction_id));
create policy receipts_insert on public.receipt_attachments for insert to authenticated
  with check (
    uploaded_by = (select auth.uid())
    and exists (
      select 1 from public.transactions t
      where t.id = transaction_id
        and public.can_write_record(t.household_id, t.owner_id, t.visibility)
        and storage_path like t.household_id::text || '/' || t.id::text || '/%'
    )
  );
create policy receipts_delete on public.receipt_attachments for delete to authenticated
  using (exists (
    select 1 from public.transactions t
    where t.id = transaction_id and public.can_write_record(t.household_id, t.owner_id, t.visibility)
  ));

-- >>> 20261009000400_functions.sql
-- =====================================================================
-- OurNest Finance — RPCs, activity feed, notifications, template seed
-- =====================================================================

-- ---------------------------------------------------------------------
-- Default budget template data (editable reference data; copied into a
-- household on creation, after which the household owns its copy).
-- ---------------------------------------------------------------------
insert into public.default_budget_settings (id, total_allocation_minor) values (true, 1400000);

insert into public.default_budget_template (system_key, name, icon, color, planned_minor, sort_order) values
  ('rent',            'إيجار الشقة',          'home',          'emerald', 550000, 10),
  ('car_rent',        'إيجار السيارة',        'car',           'sky',     180000, 20),
  ('fuel',            'بنزين وسالك ومواقف',   'fuel',          'sand',     50000, 30),
  ('utilities',       'كهرباء ومياه وتكييف',  'zap',           'sand',     65000, 40),
  ('municipality',    'رسوم بلدية السكن',     'landmark',      'sage',     27500, 50),
  ('telecom',         'إنترنت وموبايلات',     'wifi',          'violet',   45000, 60),
  ('groceries',       'أكل وسوبر ماركت',      'shopping-cart', 'emerald', 170000, 70),
  ('dining',          'مطاعم وخروجات',        'utensils',      'rose',     50000, 80),
  ('shared_personal', 'مصاريف شخصية مشتركة',  'sparkles',      'violet',   40000, 90),
  ('installments',    'أقساط والتزامات',      'credit-card',   'sky',     100000, 100),
  ('emergency',       'طوارئ ومصاريف متنوعة', 'shield',        'rose',     40000, 110);

-- ---------------------------------------------------------------------
-- Activity log (shared records only) & notifications
-- ---------------------------------------------------------------------
create table public.activity_logs (
  id bigint generated always as identity primary key,
  household_id uuid not null references public.households (id) on delete cascade,
  actor_id uuid references auth.users (id) on delete set null,
  action text not null check (action in ('created', 'updated', 'deleted', 'shared', 'paid', 'contributed', 'joined')),
  entity_type text not null,
  entity_id uuid,
  title text,
  amount_minor bigint,
  created_at timestamptz not null default now()
);
create index activity_logs_household_idx on public.activity_logs (household_id, created_at desc);
create index activity_logs_entity_idx on public.activity_logs (entity_id);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  household_id uuid references public.households (id) on delete cascade,
  kind text not null check (kind in (
    'shared_expense', 'bill_due', 'bill_overdue', 'budget_warning', 'budget_exceeded',
    'installment_due', 'goal_behind', 'member_joined'
  )),
  title text not null check (char_length(title) <= 120),
  body text check (char_length(body) <= 300),
  link text check (link ~ '^/[a-z0-9/_?=&-]*$'),
  amount_minor bigint,
  actor_id uuid references auth.users (id) on delete set null,
  entity_id uuid,
  dedupe_key text check (char_length(dedupe_key) <= 120),
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint notifications_dedupe unique (user_id, dedupe_key)
);
create index notifications_user_idx on public.notifications (user_id, created_at desc);
create index notifications_entity_idx on public.notifications (entity_id);

alter table public.activity_logs enable row level security;
alter table public.notifications enable row level security;

grant select on public.activity_logs to authenticated;
grant select, delete on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;
grant insert (user_id, household_id, kind, title, body, link, amount_minor, entity_id, dedupe_key)
  on public.notifications to authenticated;

create policy activity_select on public.activity_logs for select to authenticated
  using (public.is_household_member(household_id));

create policy notifications_select on public.notifications for select to authenticated
  using (user_id = (select auth.uid()));
create policy notifications_update on public.notifications for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy notifications_delete on public.notifications for delete to authenticated
  using (user_id = (select auth.uid()));
-- A user may only create reminder-type notifications for themselves (the
-- app derives them from data that user can already read).
create policy notifications_insert_self on public.notifications for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and kind in ('bill_due', 'bill_overdue', 'budget_warning', 'budget_exceeded', 'installment_due', 'goal_behind')
    and (household_id is null or public.is_household_member(household_id))
  );

-- Title used in the activity feed for a row of any tracked table.
create or replace function public.activity_title(p_table text, p_row jsonb)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_title text;
begin
  if p_table = 'transactions' then
    v_title := nullif(trim(p_row ->> 'description'), '');
    if v_title is null then
      select c.name into v_title from public.categories c where c.id = (p_row ->> 'category_id')::uuid;
    end if;
  else
    v_title := p_row ->> 'name';
  end if;
  return left(coalesce(v_title, ''), 120);
end;
$$;

-- Logs activity for shared records and notifies the other spouse about
-- new shared expenses. Private records never produce log rows or
-- notifications. When a record becomes private, every earlier trace of
-- it in the feed and in notifications is removed.
create or replace function public.log_shared_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := (select auth.uid());
  v_new jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
  v_old jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  v_row jsonb := coalesce(v_new, v_old);
  v_action text;
  v_member record;
  v_amount bigint;
begin
  if tg_op = 'INSERT' then
    if v_new ->> 'visibility' <> 'shared' then return new; end if;
    v_action := 'created';
  elsif tg_op = 'UPDATE' then
    if v_old ->> 'visibility' = 'shared' and v_new ->> 'visibility' = 'private' then
      delete from public.activity_logs where entity_id = (v_old ->> 'id')::uuid;
      delete from public.notifications where entity_id = (v_old ->> 'id')::uuid;
      return new;
    elsif v_new ->> 'visibility' <> 'shared' then
      return new;
    elsif v_old ->> 'visibility' = 'private' then
      v_action := 'shared';
    else
      -- Ignore no-op updates (only bookkeeping columns changed).
      if (v_new - 'updated_at' - 'last_edited_by') = (v_old - 'updated_at' - 'last_edited_by') then
        return new;
      end if;
      v_action := 'updated';
    end if;
  else
    if v_old ->> 'visibility' <> 'shared' then return old; end if;
    -- Cascading delete of the whole household: nothing left to log into.
    if not exists (select 1 from public.households where id = (v_old ->> 'household_id')::uuid) then
      return old;
    end if;
    v_action := 'deleted';
  end if;

  v_amount := coalesce(
    (v_row ->> 'amount_minor')::bigint,
    (v_row ->> 'target_minor')::bigint,
    (v_row ->> 'monthly_amount_minor')::bigint
  );

  insert into public.activity_logs (household_id, actor_id, action, entity_type, entity_id, title, amount_minor)
  values (
    (v_row ->> 'household_id')::uuid, v_actor, v_action, tg_table_name,
    case when tg_op = 'DELETE' then null else (v_row ->> 'id')::uuid end,
    public.activity_title(tg_table_name, v_row), v_amount
  );

  if tg_table_name = 'transactions' and v_action in ('created', 'shared') then
    for v_member in
      select m.user_id
      from public.household_members m
      join public.user_settings s on s.user_id = m.user_id
      where m.household_id = (v_row ->> 'household_id')::uuid
        and m.user_id is distinct from v_actor
        and s.notify_shared_expenses
    loop
      insert into public.notifications (user_id, household_id, kind, title, body, link, amount_minor, actor_id, entity_id, dedupe_key)
      values (
        v_member.user_id, (v_row ->> 'household_id')::uuid, 'shared_expense',
        'مصروف مشترك جديد', public.activity_title(tg_table_name, v_row), '/expenses',
        v_amount, v_actor, (v_row ->> 'id')::uuid, 'tx:' || (v_row ->> 'id') || ':' || v_action
      )
      on conflict (user_id, dedupe_key) do nothing;
    end loop;
  end if;

  if tg_op = 'DELETE' then
    -- The entity no longer exists: earlier feed rows keep their text, but
    -- notifications pointing at it are pruned.
    delete from public.notifications where entity_id = (v_old ->> 'id')::uuid;
    return old;
  end if;
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array['transactions', 'recurring_bills', 'installment_plans', 'savings_goals'] loop
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function public.log_shared_activity()',
      t || '_activity', t
    );
  end loop;
end;
$$;

-- Child-row activity (installment payments, savings contributions):
-- logged only when the parent record is shared.
create or replace function public.log_child_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_parent record;
begin
  if tg_op <> 'INSERT' then return coalesce(new, old); end if;
  if tg_table_name = 'installment_payments' then
    select household_id, visibility, name into v_parent from public.installment_plans where id = new.plan_id;
    if found and v_parent.visibility = 'shared' then
      insert into public.activity_logs (household_id, actor_id, action, entity_type, entity_id, title, amount_minor)
      values (v_parent.household_id, (select auth.uid()), 'paid', 'installment_payments', new.plan_id, v_parent.name, new.amount_minor);
    end if;
  elsif tg_table_name = 'savings_contributions' then
    select household_id, visibility, name into v_parent from public.savings_goals where id = new.goal_id;
    if found and v_parent.visibility = 'shared' then
      insert into public.activity_logs (household_id, actor_id, action, entity_type, entity_id, title, amount_minor)
      values (v_parent.household_id, (select auth.uid()), 'contributed', 'savings_contributions', new.goal_id, v_parent.name, new.amount_minor);
    end if;
  end if;
  return new;
end;
$$;

create trigger installment_payments_activity after insert on public.installment_payments
  for each row execute function public.log_child_activity();
create trigger savings_contributions_activity after insert on public.savings_contributions
  for each row execute function public.log_child_activity();

-- Deleting an installment payment removes the expense it created, so the
-- budget never keeps a phantom payment (and vice versa via FK cascade).
create or replace function public.delete_payment_transaction()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.transaction_id is not null then
    delete from public.transactions where id = old.transaction_id;
  end if;
  return old;
end;
$$;

create trigger installment_payments_cleanup after delete on public.installment_payments
  for each row execute function public.delete_payment_transaction();

-- ---------------------------------------------------------------------
-- Seed a new household's categories + first month budget from template
-- ---------------------------------------------------------------------
create or replace function public.seed_household_defaults(p_household_id uuid, p_owner_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_budget_id uuid;
  v_month date := date_trunc('month', (now() at time zone 'Asia/Dubai'))::date;
begin
  insert into public.categories (household_id, owner_id, visibility, name, icon, color, system_key, sort_order)
  select p_household_id, p_owner_id, 'shared', t.name, t.icon, t.color, t.system_key, t.sort_order
  from public.default_budget_template t;

  insert into public.budgets (household_id, month, total_allocation_minor, created_by)
  values (p_household_id, v_month, (select total_allocation_minor from public.default_budget_settings), p_owner_id)
  returning id into v_budget_id;

  insert into public.budget_items (budget_id, household_id, category_id, planned_minor)
  select v_budget_id, p_household_id, c.id, t.planned_minor
  from public.categories c
  join public.default_budget_template t on t.system_key = c.system_key
  where c.household_id = p_household_id;
end;
$$;

-- ---------------------------------------------------------------------
-- create_household(): caller becomes the first member
-- ---------------------------------------------------------------------
create or replace function public.create_household(p_name text default 'بيتنا')
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_household_id uuid;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = 'P0001';
  end if;
  if exists (select 1 from public.household_members where user_id = v_uid) then
    raise exception 'already_in_household' using errcode = 'P0001';
  end if;

  insert into public.households (name, created_by)
  values (coalesce(nullif(trim(p_name), ''), 'بيتنا'), v_uid)
  returning id into v_household_id;

  insert into public.household_members (household_id, user_id, joined_via)
  values (v_household_id, v_uid, 'created');

  perform public.seed_household_defaults(v_household_id, v_uid);
  return v_household_id;
end;
$$;

-- ---------------------------------------------------------------------
-- Invitations
-- ---------------------------------------------------------------------
create or replace function public.create_invitation(p_email text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_household_id uuid;
  v_email text := lower(trim(p_email));
  v_token text;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = 'P0001';
  end if;
  v_household_id := public.my_household_id();
  if v_household_id is null then
    raise exception 'no_household' using errcode = 'P0001';
  end if;
  if (select count(*) from public.household_members where household_id = v_household_id) >= 2 then
    raise exception 'household_full' using errcode = 'P0001';
  end if;
  if v_email is null or v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'invalid_email' using errcode = 'P0001';
  end if;
  if v_email = (select lower(email) from auth.users where id = v_uid) then
    raise exception 'cannot_invite_self' using errcode = 'P0001';
  end if;

  update public.invitations set status = 'revoked'
  where household_id = v_household_id and status = 'pending';

  v_token := encode(extensions.gen_random_bytes(24), 'hex');
  insert into public.invitations (household_id, email, token_hash, invited_by)
  values (v_household_id, v_email, encode(extensions.digest(v_token, 'sha256'), 'hex'), v_uid);

  return v_token;
end;
$$;

create or replace function public.revoke_invitation(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.invitations
  set status = 'revoked'
  where id = p_invitation_id
    and status = 'pending'
    and public.is_household_member(household_id);
  if not found then
    raise exception 'invitation_not_found' using errcode = 'P0001';
  end if;
end;
$$;

-- Minimal, non-sensitive preview for the invitation landing page.
create or replace function public.get_invitation(p_token text)
returns table (household_name text, inviter_name text, email_hint text, status text)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_inv public.invitations%rowtype;
begin
  if p_token is null or p_token !~ '^[0-9a-f]{48}$' then
    return;
  end if;
  select * into v_inv from public.invitations
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex');
  if not found then
    return;
  end if;

  return query
  select
    h.name,
    coalesce(p.display_name, ''),
    left(split_part(v_inv.email, '@', 1), 2) || '•••@' || split_part(v_inv.email, '@', 2),
    case
      when v_inv.status = 'pending' and v_inv.expires_at < now() then 'expired'
      else v_inv.status::text
    end
  from public.households h
  left join public.profiles p on p.id = v_inv.invited_by
  where h.id = v_inv.household_id;
end;
$$;

create or replace function public.accept_invitation(p_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_email text;
  v_inv public.invitations%rowtype;
  v_existing uuid;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = 'P0001';
  end if;
  if p_token is null or p_token !~ '^[0-9a-f]{48}$' then
    raise exception 'invitation_not_found' using errcode = 'P0001';
  end if;

  select lower(email) into v_email from auth.users where id = v_uid;

  select * into v_inv from public.invitations
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  for update;

  if not found then
    raise exception 'invitation_not_found' using errcode = 'P0001';
  end if;

  select household_id into v_existing from public.household_members where user_id = v_uid;
  if v_existing = v_inv.household_id then
    return v_existing; -- already joined (idempotent)
  end if;

  if v_inv.status <> 'pending' then
    raise exception 'invitation_not_pending' using errcode = 'P0001';
  end if;
  if v_inv.expires_at < now() then
    raise exception 'invitation_expired' using errcode = 'P0001';
  end if;
  if v_inv.email <> v_email then
    raise exception 'invitation_email_mismatch' using errcode = 'P0001';
  end if;

  if v_existing is not null then
    -- A solo household with no financial records can be discarded so the
    -- spouse can join. Anything with data must be handled explicitly.
    if (select count(*) from public.household_members where household_id = v_existing) = 1
       and not exists (select 1 from public.transactions where household_id = v_existing)
       and not exists (select 1 from public.recurring_bills where household_id = v_existing)
       and not exists (select 1 from public.installment_plans where household_id = v_existing)
       and not exists (select 1 from public.savings_goals where household_id = v_existing)
       and not exists (select 1 from public.financial_accounts where household_id = v_existing)
       and not exists (select 1 from public.income_sources where owner_id = v_uid)
    then
      delete from public.households where id = v_existing;
    else
      raise exception 'already_in_household' using errcode = 'P0001';
    end if;
  end if;

  insert into public.household_members (household_id, user_id, joined_via)
  values (v_inv.household_id, v_uid, 'invitation');

  update public.invitations
  set status = 'accepted', accepted_by = v_uid, accepted_at = now()
  where id = v_inv.id;

  insert into public.activity_logs (household_id, actor_id, action, entity_type, entity_id, title)
  values (v_inv.household_id, v_uid, 'joined', 'household_members', v_uid,
          (select display_name from public.profiles where id = v_uid));

  insert into public.notifications (user_id, household_id, kind, title, body, link, actor_id, dedupe_key)
  values (v_inv.invited_by, v_inv.household_id, 'member_joined', 'انضم شريكك إلى البيت',
          (select display_name from public.profiles where id = v_uid), '/more/household', v_uid,
          'joined:' || v_uid::text)
  on conflict (user_id, dedupe_key) do nothing;

  return v_inv.household_id;
end;
$$;

-- ---------------------------------------------------------------------
-- ensure_month_budget(): returns the budget for a month, creating it by
-- copying the most recent budget (or the template) when missing.
-- Runs as the caller, so RLS still applies.
-- ---------------------------------------------------------------------
create or replace function public.ensure_month_budget(p_month date)
returns uuid
language plpgsql
set search_path = ''
as $$
declare
  v_household_id uuid := public.my_household_id();
  v_month date := date_trunc('month', p_month)::date;
  v_budget_id uuid;
  v_source record;
begin
  if v_household_id is null then
    raise exception 'no_household' using errcode = 'P0001';
  end if;

  select id into v_budget_id from public.budgets where household_id = v_household_id and month = v_month;
  if found then
    return v_budget_id;
  end if;

  select id, total_allocation_minor into v_source
  from public.budgets
  where household_id = v_household_id
  order by (month < v_month) desc, abs(month - v_month)
  limit 1;

  insert into public.budgets (household_id, month, total_allocation_minor)
  values (
    v_household_id, v_month,
    coalesce(v_source.total_allocation_minor, (select total_allocation_minor from public.default_budget_settings), 0)
  )
  on conflict (household_id, month) do nothing
  returning id into v_budget_id;

  if v_budget_id is null then
    select id into v_budget_id from public.budgets where household_id = v_household_id and month = v_month;
    return v_budget_id;
  end if;

  if v_source.id is not null then
    insert into public.budget_items (budget_id, household_id, category_id, planned_minor)
    select v_budget_id, v_household_id, bi.category_id, bi.planned_minor
    from public.budget_items bi
    join public.categories c on c.id = bi.category_id and not c.is_archived
    where bi.budget_id = v_source.id;
  end if;

  return v_budget_id;
end;
$$;

-- ---------------------------------------------------------------------
-- record_installment_payment(): payment + matching expense, atomically.
-- Runs as the caller (RLS applies).
-- ---------------------------------------------------------------------
create or replace function public.record_installment_payment(
  p_plan_id uuid,
  p_amount_minor bigint,
  p_paid_on date,
  p_period date default null,
  p_create_transaction boolean default true,
  p_payment_method public.payment_method default null,
  p_account_id uuid default null
)
returns uuid
language plpgsql
set search_path = ''
as $$
declare
  v_plan public.installment_plans%rowtype;
  v_paid bigint;
  v_outstanding bigint;
  v_tx_id uuid;
  v_payment_id uuid;
begin
  select * into v_plan from public.installment_plans where id = p_plan_id;
  if not found then
    raise exception 'plan_not_found' using errcode = 'P0001';
  end if;
  if p_amount_minor is null or p_amount_minor <= 0 then
    raise exception 'invalid_amount' using errcode = 'P0001';
  end if;

  select coalesce(sum(amount_minor), 0) into v_paid from public.installment_payments where plan_id = p_plan_id;
  v_outstanding := v_plan.total_amount_minor - v_plan.opening_paid_minor - v_paid;
  if p_amount_minor > v_outstanding then
    raise exception 'amount_exceeds_outstanding' using errcode = 'P0001';
  end if;

  if p_create_transaction then
    if v_plan.category_id is null then
      raise exception 'plan_has_no_category' using errcode = 'P0001';
    end if;
    insert into public.transactions (
      household_id, owner_id, visibility, amount_minor, category_id, account_id,
      payment_method, description, occurred_on, installment_plan_id
    ) values (
      v_plan.household_id, (select auth.uid()), v_plan.visibility, p_amount_minor, v_plan.category_id, p_account_id,
      p_payment_method, left('قسط: ' || v_plan.name, 200), p_paid_on, v_plan.id
    ) returning id into v_tx_id;
  end if;

  insert into public.installment_payments (plan_id, amount_minor, paid_on, period, is_extra, transaction_id)
  values (p_plan_id, p_amount_minor, p_paid_on, p_period, p_period is null, v_tx_id)
  returning id into v_payment_id;

  return v_payment_id;
end;
$$;

-- ---------------------------------------------------------------------
-- Grants for RPCs
-- ---------------------------------------------------------------------
revoke all on function
  public.activity_title(text, jsonb), public.log_shared_activity(), public.log_child_activity(),
  public.delete_payment_transaction(), public.seed_household_defaults(uuid, uuid),
  public.create_household(text), public.create_invitation(text), public.revoke_invitation(uuid),
  public.get_invitation(text), public.accept_invitation(text), public.ensure_month_budget(date),
  public.record_installment_payment(uuid, bigint, date, date, boolean, public.payment_method, uuid)
from public, anon, authenticated;

grant execute on function
  public.create_household(text), public.create_invitation(text), public.revoke_invitation(uuid),
  public.accept_invitation(text), public.ensure_month_budget(date),
  public.record_installment_payment(uuid, bigint, date, date, boolean, public.payment_method, uuid)
to authenticated;

grant execute on function public.get_invitation(text) to anon, authenticated;

-- >>> 20261009000500_storage.sql
-- =====================================================================
-- OurNest Finance — private receipt storage
-- Object path: {household_id}/{transaction_id}/{random}.{ext}
-- Reading a file requires a receipt_attachments row the caller can see
-- (which in turn requires access to the transaction under RLS).
-- =====================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'receipts', 'receipts', false, 10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'application/pdf']
)
on conflict (id) do update set public = false;

create or replace function public.receipt_path_writable(p_name text)
returns boolean
language plpgsql
stable
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_transaction_id uuid;
begin
  begin
    v_household_id := split_part(p_name, '/', 1)::uuid;
    v_transaction_id := split_part(p_name, '/', 2)::uuid;
  exception when others then
    return false;
  end;
  if split_part(p_name, '/', 3) = '' or split_part(p_name, '/', 4) <> '' then
    return false;
  end if;
  return exists (
    select 1 from public.transactions t
    where t.id = v_transaction_id
      and t.household_id = v_household_id
      and public.can_write_record(t.household_id, t.owner_id, t.visibility)
  );
end;
$$;

revoke all on function public.receipt_path_writable(text) from public, anon;
grant execute on function public.receipt_path_writable(text) to authenticated;

create policy "receipts_read_visible" on storage.objects for select to authenticated
  using (
    bucket_id = 'receipts'
    and exists (select 1 from public.receipt_attachments r where r.storage_path = objects.name)
  );

create policy "receipts_upload_writable" on storage.objects for insert to authenticated
  with check (bucket_id = 'receipts' and public.receipt_path_writable(name));

create policy "receipts_delete_writable" on storage.objects for delete to authenticated
  using (bucket_id = 'receipts' and public.receipt_path_writable(name));

-- >>> 20261009000600_backfill_profiles.sql
-- =====================================================================
-- Backfill profile + settings rows for accounts created before the
-- schema existed (e.g. signing up right after deployment, before
-- setup.sql was run). Idempotent: safe to run any number of times.
-- =====================================================================
insert into public.profiles (id, display_name)
select u.id,
       left(coalesce(nullif(trim(u.raw_user_meta_data ->> 'display_name'), ''), split_part(u.email, '@', 1), ''), 60)
from auth.users u
on conflict (id) do nothing;

insert into public.user_settings (user_id)
select u.id from auth.users u
on conflict (user_id) do nothing;

-- >>> 20261009000700_ensure_my_profile.sql
-- =====================================================================
-- OurNest Finance (بيتنا) — Self-heal missing profile/settings rows.
--
-- Complements 20261009000600_backfill_profiles.sql: if an account still
-- has no profiles / user_settings row at login, the app calls this RPC
-- instead of failing with "تعذّر تحميل البيانات". Idempotent.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Self-heal on login: creates the caller's missing rows, if any.
-- The app calls this when either row is absent.
-- ---------------------------------------------------------------------
create or replace function public.ensure_my_profile()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  insert into public.profiles (id, display_name)
  select
    u.id,
    left(coalesce(nullif(trim(u.raw_user_meta_data ->> 'display_name'), ''), split_part(u.email, '@', 1), ''), 60)
  from auth.users u
  where u.id = v_uid
  on conflict (id) do nothing;

  insert into public.user_settings (user_id) values (v_uid)
  on conflict (user_id) do nothing;
end;
$$;

revoke all on function public.ensure_my_profile() from public, anon;
grant execute on function public.ensure_my_profile() to authenticated;
